### ISSUE TITLE
Exporting and Importing Menu results in error

### ISSUE THREAD

**Issue by jg-development** [SnowdogApps/magento2-menu#183]
I exported my menu and was trying to import it again with the created yaml file.
I get the following error:
The following menu required import fields are missing: "css_class".

The content of the exported yaml file
```
title: Menu
identifier: main
css_class: null
creation_time: '2021-05-13 17:54:42'
update_time: '2021-05-13 17:57:26'
is_active: '1'
stores:
  - de
nodes:
  -
    type: category
    content: '1'
    classes: null
    title: Test
    target: '0'
    image: null
    image_alt_text: null
    node_template: null
    submenu_template: null
    creation_time: '2021-05-13 17:54:42'
    update_time: '2021-05-13 17:54:42'
    is_active: '1'
```

The export file should be importable without modification
